### ISSUE TITLE
TypeError when parsing headers in 0.11

### ISSUE THREAD

**Issue by fanto666** [croessner/vrfydmn#12]
I am getting following errors:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Milter/__init__.py", line 770, in <lambda>
    milter.set_eoh_callback(lambda ctx: ctx.getpriv().eoh())
  File "/usr/sbin/vrfydmn", line 199, in eoh
    if "@" in component:
TypeError: a bytes-like object is required, not 'str'

and:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Milter/__init__.py", line 772, in <lambda>
    milter.set_eom_callback(lambda ctx: ctx.getpriv().eom())
  File "/usr/sbin/vrfydmn", line 341, in eom
    new_from = " ".join([s for s, _ in decoded_from])
TypeError: sequence item 0: expected str instance, bytes found

**Comment by fanto666** [comment]
It seems that "component" and "decoded_from" are sometimes defined as "bytes", thus they need decoding to a str.

**Comment by fanto666** [comment]
I see that the first part was already fixed in #5

**Comment by fanto666** [comment]
this patch should fix decoding of From: header fields, which can appear as array of differently encoded words

[vrfydmn-decode.patch](https://github.com/user-attachments/files/16562689/vrfydmn-decode.patch)

**Comment by croessner** [comment]
Sorry for the delay. I am really busy at the moment... Anyways, could you please make a PR for this?
